name: Python Tests with Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html allure-pytest

      - name: Run tests
        run: |
          mkdir -p allure-results
          pytest --alluredir=allure-results --capture=sys -v

      - name: Generate Allure Report
        uses: qameta/allure-report-action@v1.2
        with:
          results: allure-results
