name: Python Tests with Allure and HTML Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html allure-pytest

      - name: Run Pytest (Generate Allure + HTML reports)
        run: |
          mkdir -p allure-results report
          pytest tests --alluredir=allure-results --html=report/pytest-report.html --self-contained-html --disable-warnings -v

      - name: Download Allure CLI
        run: |
          ALLURE_VERSION=2.30.0
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.tgz -O allure.tgz
          tar -zxvf allure.tgz
          sudo mv allure-${ALLURE_VERSION} /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report/pytest-report.html
