name: Python Tests with Allure and HTML Reports (Chrome + Edge)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, edge]   # Run tests on both browsers

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html allure-pytest selenium webdriver-manager

      - name: Install Browsers and Drivers
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo apt-get install -y microsoft-edge-stable
          wget https://msedgedriver.azureedge.net/117.0.2045.43/edgedriver_linux64.zip -O edgedriver.zip
          unzip edgedriver.zip -d $HOME
          sudo mv $HOME/msedgedriver /usr/bin/msedgedriver

      - name: Run Pytest (Generate Allure + HTML reports)
        run: |
          mkdir -p allure-results report
          pytest tests --alluredir=allure-results --html=report/pytest-report-${{ matrix.browser }}.html --self-contained-html --disable-warnings -v -o browser=${{ matrix.browser }}

      - name: Download Allure CLI
        run: |
          ALLURE_VERSION=2.30.0
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.tgz -O allure.tgz
          tar -zxvf allure.tgz
          sudo mv allure-${ALLURE_VERSION} /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report-${{ matrix.browser }}
          path: report/pytest-report-${{ matrix.browser }}.html
